import Vue from 'vue';
import VueMdijs from 'vue-mdijs';
import {
  mdiMagnify,
  mdiMessageProcessing,
  mdiPencil,
  mdiCog,
  mdiPencilBoxMultiple,
  mdiDelete,
  mdiPlus,
  mdiMinus,
  mdiTranslate,
  mdiChevronDown,
  mdiClose,
  mdiCheck,
  mdiLinkLock,
  mdiLink,
  mdiMenu,
  mdiEmail,
  mdiArrowRight,
  mdiKey,
  mdiEye,
  mdiEyeOff,
  mdiAccount,
  mdiDotsHorizontal,
  mdiLogout,
  mdiChartAreasplineVariant,
  mdiHistory,
  mdiGoogleChrome,
  mdiWeatherNight
} from '@mdi/js';

VueMdijs.add({
  mdiMagnify,
  mdiMessageProcessing,
  mdiPencil,
  mdiCog,
  mdiPlus,
  mdiMinus,
  mdiPencilBoxMultiple,
  mdiDelete,
  mdiTranslate,
  mdiChevronDown,
  mdiClose,
  mdiCheck,
  mdiLinkLock,
  mdiLink,
  mdiMenu,
  mdiEmail,
  mdiArrowRight,
  mdiKey,
  mdiEye,
  mdiEyeOff,
  mdiAccount,
  mdiDotsHorizontal,
  mdiLogout,
  mdiChartAreasplineVariant,
  mdiHistory,
  mdiGoogleChrome,
  mdiWeatherNight
});

Vue.use(VueMdijs);
